# Generated by Django 3.1.7 on 2021-02-21 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=8)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('SP', 'Spring'), ('SM', 'Summer'), ('FL', 'Fall')], max_length=2)),
                ('year', models.IntegerField(default=2021)),
                ('lecture_days', models.CharField(max_length=30)),
                ('lecture_time', models.CharField(max_length=100)),
                ('recitation_days', models.CharField(blank=True, max_length=30)),
                ('recitation_time', models.CharField(blank=True, max_length=100)),
                ('office_days', models.CharField(blank=True, max_length=30)),
                ('office_time', models.CharField(blank=True, max_length=100)),
                ('zoom', models.CharField(blank=True, max_length=300)),
                ('discord', models.CharField(blank=True, max_length=300)),
                ('slack', models.CharField(blank=True, max_length=300)),
                ('groupme', models.CharField(blank=True, max_length=300)),
                ('tophat', models.CharField(blank=True, max_length=300)),
                ('canvas', models.CharField(blank=True, max_length=300)),
                ('gradescope', models.CharField(blank=True, max_length=300)),
                ('box', models.CharField(blank=True, max_length=300)),
                ('website', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
