# Generated by Django 3.1.7 on 2021-02-20 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('instructor', models.CharField(max_length=50)),
                ('term', models.CharField(choices=[('SP', 'Spring'), ('SM', 'Summer'), ('FL', 'Fall')], max_length=2)),
                ('year', models.IntegerField(default=2021)),
                ('lecture_days', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tueday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=30)),
                ('lecture_times', models.CharField(max_length=30)),
                ('recitation_days', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tueday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], max_length=30)),
                ('recitation_times', models.CharField(max_length=30)),
                ('zoom', models.CharField(max_length=300)),
                ('discord', models.CharField(max_length=300)),
                ('slack', models.CharField(max_length=300)),
                ('groupme', models.CharField(max_length=300)),
                ('tophat', models.CharField(max_length=300)),
                ('gradescope', models.CharField(max_length=300)),
            ],
        ),
    ]
