# Generated by Django 3.1.7 on 2021-02-20 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_class_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='department',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
    ]
