# Generated by Django 3.1.7 on 2021-02-20 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_class_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='lecture_times',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='recitation_times',
            field=models.CharField(max_length=100),
        ),
    ]
