# Generated by Django 3.1.7 on 2021-02-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210220_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='office_days',
            field=models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tueday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday')], default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='office_times',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='class',
            name='discord',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='class',
            name='gradescope',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='class',
            name='groupme',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='class',
            name='slack',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='class',
            name='tophat',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='class',
            name='zoom',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
