# Generated by Django 3.1.7 on 2021-02-20 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210220_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='lecture_times',
            new_name='lecture_time',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='office_times',
            new_name='office_time',
        ),
        migrations.RenameField(
            model_name='class',
            old_name='recitation_times',
            new_name='recitation_time',
        ),
    ]
