# Generated by Django 3.1.7 on 2021-02-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210220_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='office_days',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='class',
            name='office_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='recitation_days',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='class',
            name='recitation_time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
