# Generated by Django 3.1.7 on 2021-02-20 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210220_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='canvas',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
